In [2]:
import numpy as np

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
X = iris.data

In [7]:
#X

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# class 0 ---> [1,0,0]
# class 1 ---> [0,1,0]
# class 2 ---> [0,0,1]

In [9]:
from tensorflow.keras.utils import to_categorical

In [10]:
y = to_categorical(y)

In [22]:
#y

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler_object = MinMaxScaler()

In [15]:
scaler_object.fit(X_train)

MinMaxScaler()

In [16]:
scaled_X_train = scaler_object.transform(X_train)

In [17]:
scaled_X_test = scaler_object.transform(X_test)

In [31]:
#scaled_X_train

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(scaled_X_train, y_train, epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.0968 - accuracy: 0.4000 - 385ms/epoch - 96ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0945 - accuracy: 0.4200 - 3ms/epoch - 750us/step
Epoch 3/150
4/4 - 0s - loss: 1.0923 - accuracy: 0.4500 - 3ms/epoch - 747us/step
Epoch 4/150
4/4 - 0s - loss: 1.0903 - accuracy: 0.4700 - 3ms/epoch - 749us/step
Epoch 5/150
4/4 - 0s - loss: 1.0884 - accuracy: 0.4800 - 5ms/epoch - 1ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0866 - accuracy: 0.5000 - 5ms/epoch - 1ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0850 - accuracy: 0.5000 - 3ms/epoch - 746us/step
Epoch 8/150
4/4 - 0s - loss: 1.0837 - accuracy: 0.5000 - 3ms/epoch - 742us/step
Epoch 9/150
4/4 - 0s - loss: 1.0821 - accuracy: 0.5100 - 4ms/epoch - 1ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0805 - accuracy: 0.5200 - 4ms/epoch - 1ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0787 - accuracy: 0.5300 - 3ms/epoch - 750us/step
Epoch 12/150
4/4 - 0s - loss: 1.0771 - accuracy: 0.5500 - 3ms/epoch - 751us/step
Epoch 13/150
4/4 - 0s - loss: 1.0754 - accur

Epoch 103/150
4/4 - 0s - loss: 0.6628 - accuracy: 0.6600 - 4ms/epoch - 999us/step
Epoch 104/150
4/4 - 0s - loss: 0.6584 - accuracy: 0.6600 - 3ms/epoch - 750us/step
Epoch 105/150
4/4 - 0s - loss: 0.6538 - accuracy: 0.6600 - 4ms/epoch - 1ms/step
Epoch 106/150
4/4 - 0s - loss: 0.6499 - accuracy: 0.6600 - 4ms/epoch - 1000us/step
Epoch 107/150
4/4 - 0s - loss: 0.6460 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 108/150
4/4 - 0s - loss: 0.6422 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 109/150
4/4 - 0s - loss: 0.6385 - accuracy: 0.6600 - 4ms/epoch - 999us/step
Epoch 110/150
4/4 - 0s - loss: 0.6348 - accuracy: 0.6600 - 3ms/epoch - 750us/step
Epoch 111/150
4/4 - 0s - loss: 0.6310 - accuracy: 0.6600 - 4ms/epoch - 1ms/step
Epoch 112/150
4/4 - 0s - loss: 0.6272 - accuracy: 0.6600 - 4ms/epoch - 999us/step
Epoch 113/150
4/4 - 0s - loss: 0.6236 - accuracy: 0.6600 - 3ms/epoch - 749us/step
Epoch 114/150
4/4 - 0s - loss: 0.6204 - accuracy: 0.6600 - 3ms/epoch - 750us/step
Epoch 115/150
4/4 - 0s 

In [23]:
model.predict(scaled_X_test)

array([[0.04724993, 0.51226586, 0.44048423],
       [0.95841885, 0.02213687, 0.01944424],
       [0.02072101, 0.5218592 , 0.45741978],
       [0.05837749, 0.5134491 , 0.42817342],
       [0.03389582, 0.50031316, 0.46579093],
       [0.9243793 , 0.03975258, 0.03586812],
       [0.15032521, 0.49478602, 0.35488883],
       [0.03421157, 0.49988833, 0.46590006],
       [0.04547441, 0.4860781 , 0.4684475 ],
       [0.07935195, 0.50885105, 0.41179693],
       [0.04084786, 0.51395804, 0.44519413],
       [0.922271  , 0.04044768, 0.03728136],
       [0.95243126, 0.02480081, 0.02276795],
       [0.9281357 , 0.0376959 , 0.03416844],
       [0.9819709 , 0.00936461, 0.00866459],
       [0.07633448, 0.53403807, 0.3896275 ],
       [0.03150697, 0.5036122 , 0.46488082],
       [0.07043467, 0.5010102 , 0.4285552 ],
       [0.07058225, 0.5157329 , 0.41368493],
       [0.03468698, 0.49925336, 0.46605968],
       [0.9437821 , 0.02927839, 0.02693955],
       [0.04837761, 0.51157427, 0.44004807],
       [0.

In [24]:
np.argmax(model.predict(scaled_X_test), axis=-1)

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
predictions = model.predict(scaled_X_test)


In [38]:
# Output is the same as y_test.argmax
predictions

array([[0.04724993, 0.51226586, 0.44048423],
       [0.95841885, 0.02213687, 0.01944424],
       [0.02072101, 0.5218592 , 0.45741978],
       [0.05837749, 0.5134491 , 0.42817342],
       [0.03389582, 0.50031316, 0.46579093],
       [0.9243793 , 0.03975258, 0.03586812],
       [0.15032521, 0.49478602, 0.35488883],
       [0.03421157, 0.49988833, 0.46590006],
       [0.04547441, 0.4860781 , 0.4684475 ],
       [0.07935195, 0.50885105, 0.41179693],
       [0.04084786, 0.51395804, 0.44519413],
       [0.922271  , 0.04044768, 0.03728136],
       [0.95243126, 0.02480081, 0.02276795],
       [0.9281357 , 0.0376959 , 0.03416844],
       [0.9819709 , 0.00936461, 0.00866459],
       [0.07633448, 0.53403807, 0.3896275 ],
       [0.03150697, 0.5036122 , 0.46488082],
       [0.07043467, 0.5010102 , 0.4285552 ],
       [0.07058225, 0.5157329 , 0.41368493],
       [0.03468698, 0.49925336, 0.46605968],
       [0.9437821 , 0.02927839, 0.02693955],
       [0.04837761, 0.51157427, 0.44004807],
       [0.

In [34]:
predictions.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [36]:
from sklearn.metrics import confusion_matrix,classification_report

In [37]:
confusion_matrix(y_test.argmax(axis=1),predictions)

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets